# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  deploy:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - aws-s3/copy:
          from: ./index.html
          to: 's3://cyl-life'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"

  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: $(npm bin)/cypress run